# Generated by Django 3.2 on 2021-04-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('downloads', models.IntegerField(blank=True)),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Microsoft Office'), ('txt', 'Text'), ('doc', 'Microsoft Office (old)'), ('odt', 'OpenDocument')], max_length=50)),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
