# Generated by Django 3.2 on 2021-04-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='downloads',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
