# Generated by Django 3.2 on 2021-04-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_auto_20210416_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
    ]
